### ISSUE TITLE
Error running gitlab connector

### ISSUE THREAD

**Issue by ani1311** [onyx-dot-app/onyx#1109]
I am facing an error trying to run the GitLab connector, the date returned by Gitlab API has a timezone offset. 

Stack trace: 
```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 173, in _run_indexing
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/gitlab/connector.py", line 116, in _fetch_from_gitlab
    mr.updated_at = datetime.strptime(
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-02-20T07:57:43.874-08:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

The line with error: https://github.com/danswer-ai/danswer/blob/aa7c811a9ace1244f5f6aaf5d4bb8e1a0ea1b5bb/backend/danswer/connectors/gitlab/connector.py#L116-L118

**Comment by herveleclerc** [comment]
I make it works changing _fetch_from_gitlab func

in connector.py

```
import pytz

#...

    def _fetch_from_gitlab(
        self, start: datetime | None = None, end: datetime | None = None
    ) -> GenerateDocumentsOutput:
        if self.gitlab_client is None:
            raise ConnectorMissingCredentialError("Gitlab")
        project = self.gitlab_client.projects.get(
            f"{self.project_owner}/{self.project_name}"
        )

        if self.include_mrs:
            merge_requests = project.mergerequests.list(
                state=self.state_filter, order_by="updated_at", sort="desc"
            )

            for mr_batch in _batch_gitlab_objects(merge_requests, self.batch_size):
                doc_batch: list[Document] = []
                for mr in mr_batch:
                    mr.updated_at = datetime.strptime(
                        mr.updated_at, "%Y-%m-%dT%H:%M:%S.%f%z"
                    )
                    if start is not None and mr.updated_at < start:
                        yield doc_batch
                        return
                    if end is not None and mr.updated_at > end:
                        continue
                    doc_batch.append(_convert_merge_request_to_document(mr))
                yield doc_batch

        if self.include_issues:
            issues = project.issues.list(state=self.state_filter)

            for issue_batch in _batch_gitlab_objects(issues, self.batch_size):
                doc_batch = []
                for issue in issue_batch:
                    issue.updated_at = datetime.strptime(
                        issue.updated_at, "%Y-%m-%dT%H:%M:%S.%f%z"
                    )
                    if start is not None:
                      start = start.replace(tzinfo=pytz.UTC)
                      if issue.updated_at < start:
                        yield doc_batch
                        return
                    if end is not None:
                      end = end.replace(tzinfo=pytz.UTC)
                      if issue.updated_at > end:
                        continue

                    doc_batch.append(_convert_issue_to_document(issue))
                yield doc_batch

...

**Comment by m0wer** [comment]
Thanks a lot @herveleclerc ! I extende your fix a bit to work for MRs too, here's the complete diff:

```diff
diff --git a/backend/danswer/connectors/gitlab/connector.py b/backend/danswer/connectors/gitlab/connector.py
index 3b37dcd..e953e74 100644
--- a/backend/danswer/connectors/gitlab/connector.py
+++ b/backend/danswer/connectors/gitlab/connector.py
@@ -6,6 +6,7 @@ from datetime import timezone
 from typing import Any

 import gitlab
+import pytz

 from danswer.configs.app_configs import INDEX_BATCH_SIZE
 from danswer.configs.constants import DocumentSource
@@ -114,12 +115,12 @@ class GitlabConnector(LoadConnector, PollConnector):
                 doc_batch: list[Document] = []
                 for mr in mr_batch:
                     mr.updated_at = datetime.strptime(
-                        mr.updated_at, "%Y-%m-%dT%H:%M:%S.%fZ"
+                        mr.updated_at, "%Y-%m-%dT%H:%M:%S.%f%z"
                     )
-                    if start is not None and mr.updated_at < start:
+                    if start is not None and mr.updated_at < start.replace(tzinfo=pytz.UTC):
                         yield doc_batch
                         return
-                    if end is not None and mr.updated_at > end:
+                    if end is not None and mr.updated_at > end.replace(tzinfo=pytz.UTC):
                         continue
                     doc_batch.append(_convert_merge_request_to_document(mr))
                 yield doc_batch
@@ -131,13 +132,18 @@ class GitlabConnector(LoadConnector, PollConnector):
                 doc_batch = []
                 for issue in issue_batch:
                     issue.updated_at = datetime.strptime(
-                        issue.updated_at, "%Y-%m-%dT%H:%M:%S.%fZ"
+                        issue.updated_at, "%Y-%m-%dT%H:%M:%S.%f%z"
                     )
-                    if start is not None and issue.updated_at < start:
+                    if start is not None:
+                      start = start.replace(tzinfo=pytz.UTC)
+                      if issue.updated_at < start:
                         yield doc_batch
                         return
-                    if end is not None and issue.updated_at > end:
+                    if end is not None:
+                      end = end.replace(tzinfo=pytz.UTC)
+                      if issue.updated_at > end:
                         continue
+
                     doc_batch.append(_convert_issue_to_document(issue))
                 yield doc_batch
```

**Comment by danielnaber** [comment]
I think this issue can be closed, as https://github.com/danswer-ai/danswer/pull/1559 has been merged.
