### ISSUE TITLE
RuntimeError: Failed to prepare Vespa Danswer Index. "error-code":"INVALID_APPLICATION_PACKAGE"

### ISSUE THREAD

**Issue by commanderhanke** [onyx-dot-app/onyx#1158]
Hi,team, I have encounted an error when I try to use docker compose to deployed whole project. The error comes from danswer-stack-api_server-1 docker and the backtrace is here:
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/main.py", line 237, in lifespan
    document_index.ensure_indices_exist(
  File "/app/danswer/document_index/vespa/index.py", line 708, in ensure_indices_exist
    raise RuntimeError(
RuntimeError: Failed to prepare Vespa Danswer Index. Response: {"error-code":"INVALID_APPLICATION_PACKAGE",yy-mm-dd'>field-type-change</allow> to validation-overrides.xml, see https://docs.vespa.ai/en/reference/val

ERROR:    Application startup failed. Exiting.
Can someone tell me why this error happened? Thanks

**Comment by Daniel199438** [comment]
+1
