### ISSUE TITLE
Jira project indexing fails with attribute error

### ISSUE THREAD

**Issue by data-source** [onyx-dot-app/onyx#1194]
`Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 186, in _run_indexing
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/danswer_jira/connector.py", line 158, in poll_source
    doc_batch, fetched_batch_size = fetch_jira_issues_batch(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/danswer_jira/connector.py", line 89, in fetch_jira_issues_batch
    metadata={"label": jira.fields.labels} if jira.fields.labels else {},
                                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'PropertyHolder' object has no attribute 'labels'`

This issue is repeated with 
`AttributeError: 'PropertyHolder' object has no attribute 'description'`

Happens only on one project, many other went through fine.

**Comment by useruid** [comment]
hello, @data-source !

is it a kinda specific project where there is no description and label fields?

**Comment by data-source** [comment]
I did check and it had those fields as they're system fields

**Comment by yuhongsun96** [comment]
Can you share what kind of Jira deployment you're using? Is it on the cloud, Jira server, or something else? Also they have different API versions, do you know which API version you're using?

The default is API version 2 but you're probably on a different version.

**Comment by yuhongsun96** [comment]
Added "JIRA_API_VERSION" env variable, if you're not on version 2, try setting this in the container environment and see if it fixes things, if not we will have to dig deeper. https://docs.danswer.dev/configuration_guide

**Comment by data-source** [comment]
It's been happening on a few more projects recently. 
On one of them it indexed 560 issues and then stopped. 

```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 186, in _run_indexing
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/danswer_jira/connector.py", line 158, in poll_source
    doc_batch, fetched_batch_size = fetch_jira_issues_batch(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/danswer_jira/connector.py", line 89, in fetch_jira_issues_batch
    metadata={"label": jira.fields.labels} if jira.fields.labels else {},
                                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'PropertyHolder' object has no attribute 'labels'

```

**Comment by yuhongsun96** [comment]
Some more metadata fields were added, looks like there are some additional non-standard settings you guys are using. We can just wrap these all in a try but then these metadata fields just won't get picked up. The labels are like "tags" you can add to pages.

**Comment by scality-gaelsechaud** [comment]
Can't we ignore specific attribute maybe ?
