### ISSUE TITLE
Build problem running ./init-letsencrypt.sh on ec2

### ISSUE THREAD

**Issue by gambithunt** [onyx-dot-app/onyx#1416]
Hi

I've followed instructions and setup the **.env** file and the **.env.nginx** files with the correct domain.

When I run the script letsencrypt succeeds but then I get a bunch of errors.

When I run **docker-compose.dev.yml**  using 
```
docker compose -f docker-compose.dev.yml -p danswer-stack up -d --pull always --force-recreate
```

It works fine and I can access it at the domain using port 3000. Of course in this case there are no certificates so https does not work.

I'm trying to deploy it for production so it's important I used the correct docker-compose files as well as setting up certificates for ssl.

I would also like to setup oauth once it's all running correctly.

Any help would be most appriciated.

```
ERROR: for 209e378d187f_danswer-stack_inference_model_server_1  'ContainerConfig'

ERROR: for 51ad109bac11_danswer-stack_index_1  'ContainerConfig'

ERROR: for 48c607e5f934_danswer-stack_relational_db_1  'ContainerConfig'

ERROR: for danswer-stack_indexing_model_server_1  'ContainerConfig'

ERROR: for inference_model_server  'ContainerConfig'

ERROR: for index  'ContainerConfig'

ERROR: for relational_db  'ContainerConfig'

ERROR: for indexing_model_server  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[106529] Failed to execute script docker-compose
```

**Comment by gambithunt** [comment]
Hi, I think that it was `docker-compose` that was the issue, using `docker compose` seeming to work.
