### ISSUE TITLE
Failed indexation due to slack timeout blocks other indexations

### ISSUE THREAD

**Issue by Poltuu** [onyx-dot-app/onyx#1522]
My slack connector seems to have suffered from a timeout while indexing.
However, it looks to me like it stopped all the other indexations, that remain "scheduled", and not a single one is moving.

Whate are my options at this point

```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 177, in _run_indexing
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/slack/connector.py", line 358, in poll_source
    for document in get_all_docs(
  File "/app/danswer/connectors/slack/connector.py", line 305, in get_all_docs
    thread = get_thread(
             ^^^^^^^^^^^
  File "/app/danswer/connectors/slack/connector.py", line 133, in get_thread
    for result in _make_paginated_slack_api_call(
  File "/app/danswer/connectors/slack/utils.py", line 60, in paginated_call
    response = call(cursor=cursor, limit=_SLACK_LIMIT, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/cross_connector_utils/retry_wrapper.py", line 38, in wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/slack/utils.py", line 80, in rate_limited_call
    response = call(**kwargs)
               ^^^^^^^^^^^^^^
  File "/app/danswer/connectors/slack/utils.py", line 43, in logged_call
    result = call(**kwargs)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/client.py", line 2610, in conversations_replies
    return self.api_call("conversations.replies", http_verb="GET", params=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 294, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 495, in _perform_urllib_http_request
    raise err
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 397, in _perform_urllib_http_request
    resp = self._perform_urllib_http_request_internal(url, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 526, in _perform_urllib_http_request_internal
    resp = urlopen(req, context=self.ssl, timeout=self.timeout)  # skipcq: BAN-B310
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1386, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1315, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
```

**Comment by david-prv** [comment]
Iirc you can pause and re-run them in your admin dashboard. Just click on the corresponding task and search for a red "pause" button. After that you should be able to find a "Re-Run" button somewhere

**Comment by Poltuu** [comment]
Is there a document somewhere where I may understand how the indexing logic works ? right now, i feel like after a failed indexing, indexing jsut stop working for all connectors. everything remains at "scheduled".

**Comment by jwjordan** [comment]
I'm also running into this issue.
