### ISSUE TITLE
file connectors : Upload file

### ISSUE THREAD

**Issue by gmoulard** [onyx-dot-app/onyx#1530]
When I upload a file, with interface, I don't see nothing in interface, and I view this logs : 

danswer-stack-nginx-1                   | 172.24.0.23 - - [28/May/2024:16:18:43 +0000] "GET /api/health HTTP/1.1" 200 43 "https://danswer.moulard.org/admin/connectors/file" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "193.253.10.131"
danswer-stack-api_server-1              | INFO:     172.24.0.17:33392 - "GET /manage/admin/connector/indexing-status HTTP/1.1" 200 OK
danswer-stack-nginx-1                   | 172.24.0.23 - - [28/May/2024:16:18:43 +0000] "GET /api/manage/admin/connector/indexing-status HTTP/1.1" 200 2248 "https://danswer.moulard.org/admin/connectors/file" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "193.253.10.131"
danswer-stack-background-1              | 05/28/2024 04:18:43 PM            update.py 374 : Running update, current UTC time: 2024-05-28 16:18:43
danswer-stack-background-1              | 05/28/2024 04:18:43 PM            update.py 278 : Found 0 new indexing tasks.
danswer-stack-relational_db-1           | 2024-05-28 16:18:44.130 UTC [35] ERROR:  column file_store.display_name does not exist at character 54
danswer-stack-relational_db-1           | 2024-05-28 16:18:44.130 UTC [35] STATEMENT:  SELECT file_store.file_name AS file_store_file_name, file_store.display_name AS file_store_display_name, file_store.file_origin AS file_store_file_origin, file_store.file_type AS file_store_file_type, file_store.file_metadata AS file_store_file_metadata, file_store.lobj_oid AS file_store_lobj_oid
danswer-stack-relational_db-1           |       FROM file_store
danswer-stack-relational_db-1           |       WHERE file_store.file_name = '3b252322-2e3e-43d5-ab59-47927b583965/smallFile.txt'
danswer-stack-relational_db-1           |        LIMIT 1
danswer-stack-api_server-1              | INFO:     172.24.0.17:33402 - "POST /manage/admin/connector/file/upload HTTP/1.1" 500 Internal Server Error
danswer-stack-nginx-1                   | 172.24.0.23 - - [28/May/2024:16:18:44 +0000] "POST /api/manage/admin/connector/file/upload HTTP/1.1" 500 21 "https://danswer.moulard.org/admin/connectors/file" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "193.253.10.131"
danswer-stack-api_server-1              | ERROR:    Exception in ASGI application
danswer-stack-api_server-1              | Traceback (most recent call last):
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
danswer-stack-api_server-1              |     self.dialect.do_execute(
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
danswer-stack-api_server-1              |     cursor.execute(statement, parameters)
danswer-stack-api_server-1              | psycopg2.errors.UndefinedColumn: column file_store.display_name does not exist
danswer-stack-api_server-1              | LINE 1: ...ECT file_store.file_name AS file_store_file_name, file_store...
danswer-stack-api_server-1              |                                                              ^
danswer-stack-api_server-1              |
danswer-stack-api_server-1              |
danswer-stack-api_server-1              | The above exception was the direct cause of the following exception:
danswer-stack-api_server-1              |
danswer-stack-api_server-1              | Traceback (most recent call last):
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
danswer-stack-api_server-1              |     result = await app(  # type: ignore[func-returns-value]
danswer-stack-api_server-1              |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
danswer-stack-api_server-1              |     return await self.app(scope, receive, send)
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
danswer-stack-api_server-1              |     await super().__call__(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
danswer-stack-api_server-1              |     await self.middleware_stack(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
danswer-stack-api_server-1              |     raise exc
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
danswer-stack-api_server-1              |     await self.app(scope, receive, _send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
danswer-stack-api_server-1              |     await self.simple_response(scope, receive, send, request_headers=headers)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
danswer-stack-api_server-1              |     await self.app(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
danswer-stack-api_server-1              |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
danswer-stack-api_server-1              |     raise exc
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
danswer-stack-api_server-1              |     await app(scope, receive, sender)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
danswer-stack-api_server-1              |     await self.middleware_stack(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
danswer-stack-api_server-1              |     await route.handle(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
danswer-stack-api_server-1              |     await self.app(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
danswer-stack-api_server-1              |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
danswer-stack-api_server-1              |     raise exc
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
danswer-stack-api_server-1              |     await app(scope, receive, sender)
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
danswer-stack-api_server-1              |     response = await func(request)
danswer-stack-api_server-1              |                ^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
danswer-stack-api_server-1              |     raise e
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
danswer-stack-api_server-1              |     raw_response = await run_endpoint_function(
danswer-stack-api_server-1              |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
danswer-stack-api_server-1              |     return await run_in_threadpool(dependant.call, **values)
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
danswer-stack-api_server-1              |     return await anyio.to_thread.run_sync(func, *args)
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
danswer-stack-api_server-1              |     return await get_async_backend().run_sync_in_worker_thread(
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
danswer-stack-api_server-1              |     return await future
danswer-stack-api_server-1              |            ^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
danswer-stack-api_server-1              |     result = context.run(func, *args)
danswer-stack-api_server-1              |              ^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/app/danswer/server/documents/connector.py", line 355, in upload_files
danswer-stack-api_server-1              |     file_store.save_file(
danswer-stack-api_server-1              |   File "/app/danswer/file_store/file_store.py", line 81, in save_file
danswer-stack-api_server-1              |     upsert_pgfilestore(
danswer-stack-api_server-1              |   File "/app/danswer/db/pg_file_store.py", line 61, in upsert_pgfilestore
danswer-stack-api_server-1              |     pgfilestore = db_session.query(PGFileStore).filter_by(file_name=file_name).first()
danswer-stack-api_server-1              |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
danswer-stack-api_server-1              |     return self.limit(1)._iter().first()  # type: ignore
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
danswer-stack-api_server-1              |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
danswer-stack-api_server-1              |                                                   ^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
danswer-stack-api_server-1              |     return self._execute_internal(
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
danswer-stack-api_server-1              |     result: Result[Any] = compile_state_cls.orm_execute_statement(
danswer-stack-api_server-1              |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
danswer-stack-api_server-1              |     result = conn.execute(
danswer-stack-api_server-1              |              ^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
danswer-stack-api_server-1              |     return meth(
danswer-stack-api_server-1              |            ^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
danswer-stack-api_server-1              |     return connection._execute_clauseelement(
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
danswer-stack-api_server-1              |     ret = self._execute_context(
danswer-stack-api_server-1              |           ^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
danswer-stack-api_server-1              |     return self._exec_single_context(
danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
danswer-stack-api_server-1              |     self._handle_dbapi_exception(
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
danswer-stack-api_server-1              |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
danswer-stack-api_server-1              |     self.dialect.do_execute(
danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
danswer-stack-api_server-1              |     cursor.execute(statement, parameters)
danswer-stack-api_server-1              | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column file_store.display_name does not exist
danswer-stack-api_server-1              | LINE 1: ...ECT file_store.file_name AS file_store_file_name, file_store...
danswer-stack-api_server-1              |                                                              ^
danswer-stack-api_server-1              |
danswer-stack-api_server-1              | [SQL: SELECT file_store.file_name AS file_store_file_name, file_store.display_name AS file_store_display_name, file_store.file_origin AS file_store_file_origin, file_store.file_type AS file_store_file_type, file_store.file_metadata AS file_store_file_metadata, file_store.lobj_oid AS file_store_lobj_oid
danswer-stack-api_server-1              | FROM file_store
danswer-stack-api_server-1              | WHERE file_store.file_name = %(file_name_1)s
danswer-stack-api_server-1              |  LIMIT %(param_1)s]
danswer-stack-api_server-1              | [parameters: {'file_name_1': '3b252322-2e3e-43d5-ab59-47927b583965/smallFile.txt', 'param_1': 1}]
danswer-stack-api_server-1              | (Background on this error at: https://sqlalche.me/e/20/f405)

**Comment by gmoulard** [comment]
I have workaroun !!!

Only add some COLUMN on postgrey database !!!

docker exec -it 6fe11ac40728 psql -U postgres -W 

ALTER TABLE file_store ADD COLUMN display_name text ; 
ALTER TABLE file_store ADD COLUMN file_metadata text ;
ALTER TABLE file_store ADD COLUMN file_type text ;
ALTER TABLE file_store ADD COLUMN file_origin text ;
