### ISSUE TITLE
failed to delete connector: key error

### ISSUE THREAD

**Issue by Smensink** [onyx-dot-app/onyx#1551]
2024-06-01 17:15:53 background-1              | [2024-06-01 07:15:52,044: ERROR/MainProcess] Failed to run connector_deletion due to "XXXXXXXX"
2024-06-01 17:15:53 background-1              | Traceback (most recent call last):
2024-06-01 17:15:53 background-1              |   File "/app/danswer/background/celery/celery.py", line 83, in cleanup_connector_credential_pair_task
2024-06-01 17:15:53 background-1              |     return delete_connector_credential_pair(
2024-06-01 17:15:53 background-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-01 17:15:53 background-1              |   File "/app/danswer/background/connector_deletion.py", line 172, in delete_connector_credential_pair
2024-06-01 17:15:53 background-1              |     _delete_connector_credential_pair_batch(
2024-06-01 17:15:53 background-1              |   File "/app/danswer/background/connector_deletion.py", line 98, in _delete_connector_credential_pair_batch
2024-06-01 17:15:53 background-1              |     document_index.update(update_requests=update_requests)
2024-06-01 17:15:53 background-1              |   File "/app/danswer/document_index/vespa/index.py", line 914, in update
2024-06-01 17:15:53 background-1              |     for doc_chunk_id in all_doc_chunk_ids[document_id]:
2024-06-01 17:15:53 background-1              |                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
2024-06-01 17:15:53 background-1              | KeyError: "XXXXXXXX"
2024-06-01 17:15:53 background-1              | [2024-06-01 07:15:52,083: ERROR/MainProcess] Task danswer.background.celery.celery.cleanup_connector_credential_pair_task[742b2bfb-6681-4921-8485-f4cc5018a11f] raised unexpected: KeyError("XXXXXXX")

**Comment by kshitiz305** [comment]
Hi, could you please provide the code snippet to reproduce this?
