### ISSUE TITLE
Slack error 

### ISSUE THREAD

**Issue by data-source** [onyx-dot-app/onyx#2479]
`ERROR:    09/17/2024 02:19:28 PM             chunk_retrieval.py  309: Failed to query Vespa:
Headers: {'User-Agent': 'python-requests/2.32.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1648', 'Content-Type': 'application/json'}
Status Code: 504
Response Content: {"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":0},"coverage":{"coverage":100,"documents":0,"full":true,"nodes":0,"results":1,"resultsFull":1},"errors":[{"code":12,"summary":"Timed out","source":"danswer_index","message":"Timeout while waiting for sc0.num0"}]}}
Exception: 504 Server Error: Gateway Timeout for url: http://index:8081/search/
ERROR:    09/17/2024 02:19:29 PM             chunk_retrieval.py  309: Failed to query Vespa:
Headers: {'User-Agent': 'python-requests/2.32.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1648', 'Content-Type': 'application/json'}
Status Code: 504
Response Content: {"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":0},"coverage":{"coverage":100,"documents":0,"full":true,"nodes":0,"results":1,"resultsFull":1},"errors":[{"code":12,"summary":"Timed out","source":"danswer_index","message":"Timeout while waiting for sc0.num0"}]}}
Exception: 504 Server Error: Gateway Timeout for url: http://index:8081/search/
ERROR:    09/17/2024 02:19:32 PM             chunk_retrieval.py  309: Failed to query Vespa:
Headers: {'User-Agent': 'python-requests/2.32.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1648', 'Content-Type': 'application/json'}
Status Code: 504
Response Content: {"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":0},"coverage":{"coverage":100,"documents":0,"full":true,"nodes":0,"results":1,"resultsFull":1},"errors":[{"code":12,"summary":"Timed out","source":"danswer_index","message":"Timeout while waiting for sc0.num0"}]}}
Exception: 504 Server Error: Gateway Timeout for url: http://index:8081/search/
ERROR:    09/17/2024 02:19:32 PM       handle_regular_answer.py  269: [Channel ID: C07LHNK1C23] Unable to process message - did not successfully answer in 5 attempts
Traceback (most recent call last):
  File "/app/danswer/document_index/vespa/chunk_retrieval.py", line 301, in query_vespa
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: http://index:8081/search/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/danswer/danswerbot/slack/handlers/handle_regular_answer.py", line 253, in handle_regular_answer
    answer = _get_answer(
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "/app/danswer/danswerbot/slack/handlers/handle_regular_answer.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/danswerbot/slack/handlers/handle_regular_answer.py", line 203, in _get_answer
    answer = get_search_answer(
             ^^^^^^^^^^^^^^^^^^
  File "/app/danswer/one_shot_answer/answer_question.py", line 377, in get_search_answer
    for packet in results:
  File "/app/danswer/one_shot_answer/answer_question.py", line 238, in stream_answer_objects
    for packet in cast(AnswerObjectIterator, answer.processed_streamed_output):
  File "/app/danswer/llm/answering/answer.py", line 569, in processed_streamed_output
    for processed_packet in _process_stream(output_generator):
  File "/app/danswer/llm/answering/answer.py", line 509, in _process_stream
    for message in stream:
  File "/app/danswer/llm/answering/answer.py", line 435, in _raw_output_for_non_explicit_tool_calling_llms
    for response in tool_runner.tool_responses():
  File "/app/danswer/tools/tool_runner.py", line 30, in tool_responses
    for tool_response in self.tool.run(**self.args):
  File "/app/danswer/tools/search/search_tool.py", line 305, in run
    top_sections=search_pipeline.final_context_sections,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/search/pipeline.py", line 338, in final_context_sections
    self._final_context_sections = _merge_sections(sections=self.reranked_sections)
                                                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/search/pipeline.py", line 322, in reranked_sections
    retrieved_sections=self._get_sections(),
                       ^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/utils/timing.py", line 31, in wrapped_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/search/pipeline.py", line 263, in _get_sections
    self.document_index.id_based_retrieval(
  File "/app/danswer/document_index/vespa/index.py", line 405, in id_based_retrieval
    return batch_search_api_retrieval(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/document_index/vespa/chunk_retrieval.py", line 401, in batch_search_api_retrieval
    _get_chunks_via_batch_search(
  File "/app/danswer/document_index/vespa/chunk_retrieval.py", line 369, in _get_chunks_via_batch_search
    inference_chunks = query_vespa(params)
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "/app/danswer/document_index/vespa/chunk_retrieval.py", line 315, in query_vespa
    raise requests.HTTPError(error_base) from e
requests.exceptions.HTTPError: Failed to query Vespa
ERROR:    09/17/2024 02:19:32 PM`

**Comment by rkuo-danswer** [comment]
Hi ... how did you install Danswer and is there anything you can tell us about your configuration?
