### ISSUE TITLE
Backstack connector

### ISSUE THREAD

**Issue by Mohammed2Hussein** [onyx-dot-app/onyx#3227]
I'm trying to connect "Danswer" with "Bookstack", both of them are installed on "Docker", but always fail.

Here is stack trace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f512fd56a10>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 589, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6875): Max retries exceeded with url: /api/books?count=16&offset=0&sort=%2Bid&filter%5Bupdated_at%3Alte%5D=2024-11-23+16%3A42%3A34 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f512fd56a10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 224, in _run_indexing
    for doc_batch in connector_runner.run():
  File "/app/danswer/connectors/connector_runner.py", line 48, in run
    yield from self.doc_batch_generator
  File "/app/danswer/connectors/bookstack/connector.py", line 200, in poll_source
    doc_batch, num_results = self._get_doc_batch(
                             ^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/bookstack/connector.py", line 63, in _get_doc_batch
    batch = bookstack_client.get(endpoint, params=params).get("data", [])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/bookstack/client.py", line 29, in get
    response = requests.get(url, headers=headers, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6875): Max retries exceeded with url: /api/books?count=16&offset=0&sort=%2Bid&filter%5Bupdated_at%3Alte%5D=2024-11-23+16%3A42%3A34 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f512fd56a10>: Failed to establish a new connection: [Errno 111] Connection refused'))

------------------------------------------------------------------------------------
<img width="805" alt="Screenshot 2024-11-23 at 5 40 38 PM" src="https://github.com/user-attachments/assets/e8a8cff4-ba66-4354-9928-539e17b76908">
<img width="1741" alt="Screenshot 2024-11-23 at 5 41 35 PM" src="https://github.com/user-attachments/assets/cdf3d865-2e70-4a4c-99eb-7f74ea5ef005">

**Comment by env0j** [comment]
did you find a fix?

**Comment by Mohammed2Hussein** [comment]
Not yet

**Comment by env0j** [comment]
Are you using localhost as the domain for the connector?
Does Onyx and Bookstack run on the same server?

**Comment by Mohammed2Hussein** [comment]
I have tried using localhost as the domain for the connector. 
For Bookstack I have tried both, one on a different docker container with another port on the same server, and the second from the Bookstack demo as a test.
But all are the same result.

**Comment by Mohammed2Hussein** [comment]
I have tried again, using Bookstack demo https://demo.bookstackapp.com/

and here what I got:

`Traceback (most recent call last):
  File "/app/onyx/background/indexing/run_indexing.py", line 305, in _run_indexing
    for doc_batch in connector_runner.run():
  File "/app/onyx/connectors/connector_runner.py", line 50, in run
    for batch in self.doc_batch_generator:
  File "/app/onyx/connectors/bookstack/connector.py", line 200, in poll_source
    doc_batch, num_results = self._get_doc_batch(
                             ^^^^^^^^^^^^^^^^^^^^
  File "/app/onyx/connectors/bookstack/connector.py", line 63, in _get_doc_batch
    batch = bookstack_client.get(endpoint, params=params).get("data", [])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/onyx/connectors/bookstack/client.py", line 41, in get
    raise BookStackClientRequestFailedError(response.status_code, error)
onyx.connectors.bookstack.client.BookStackClientRequestFailedError: BookStack Client request failed with status 403: Forbidden`

**Comment by xristosNSK** [comment]
Still facing the same issue, any updates on this?
