### ISSUE TITLE
Outline KB connector (getoutline.com)

### ISSUE THREAD

**Issue by fullstackdesign-xyz** [onyx-dot-app/onyx#3256]
## Overview
Request to integrate [Outline](https://www.getoutline.com/) as a knowledge base connector, similar to the existing BookStack integration.

## Why Outline?
- **Popularity**: Widely adopted with [28k+ GitHub stars](https://github.com/outline/outline) and active development.
- **Feature-rich**: Real-time collaborative editing, Markdown support, and self-hosted/cloud-hosted options.
- **API ready**: RPC-style API with a [comprehensive OpenAPI specification](https://www.getoutline.com/developers), enabling programmatic interaction with all aspects of its data.
- **Structure fit:** Uses Collections/Documents, similar to BookStack’s model.

## Value proposition
Adding Outline support would:
- Expand Danswer’s ecosystem.
- Enable unified search across a popular knowledge platform.
- Attract Outline’s substantial user base.

---

<img width="1438" alt="screenshot" src="https://github.com/user-attachments/assets/084cc76b-e9b2-4af8-a288-cf74c6337279">

**Comment by cypris75** [comment]
We self-host Outline (via Cloudron) and we would become an Onyx customer right away if this becomes available.

**Comment by ljcatlin** [comment]
How do we resurrect this request?

**Comment by lw-miles** [comment]
We also use Outline, would be great to connect these two together, especially since Outline Business/Enterprise makes you pay for this functionality 👍

**Comment by andrea-tr2** [comment]
+1

P.s. In the meantime, there is this great MCP server:
https://github.com/mmmeff/outline-mcp-server

**Comment by Weves** [comment]
**_IMPORTANT NOTE ON THE ABOVE_**: implementation MUST have thorough tests that call a real Outline instance to verify main functionality.

**Comment by abhishek818** [comment]
@Weves can i take this up? you can perhaps set a deadline.. (this is to avoid reworks from several people).

**Comment by Myestery** [comment]
I'll like to work on this too @Weves and can get it done this weekend

**Comment by Weves** [comment]
@Myestery you got it (made a lot of progress so far). Have some comments, will add them to the PR.

**Comment by MAVRICK-1** [comment]
Hi @Weves,

I'm running the project in the `opython` environment and followed all steps in `CONTRIBUTING.md`. However, I’m encountering the following error when trying to connect to Redis:

---

#### 💥 Full Error Traceback

```
Traceback (most recent call last):
  File "/home/mavrick/anaconda3/envs/onyx-dev/lib/python3.11/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mavrick/anaconda3/envs/onyx-dev/lib/python3.11/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/mavrick/anaconda3/envs/onyx-dev/lib/python3.11/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/mavrick/anaconda3/envs/onyx-dev/lib/python3.11/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/mavrick/anaconda3/envs/onyx-dev/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused
```

This leads to:

```
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6380. Connection refused.
```

but in docker-compose.dev.yml redis is running in 6379 port.

**Comment by MuthonduG** [comment]
is this still open?

**Comment by ghost** [comment]
@Weves Are we close?

**Comment by vaultdmn** [comment]
@Weves If this issue is still open please assign it to me. Thank.

**Comment by Weves** [comment]
Thanks for the awesome PR @melmathari !

**Comment by gus-costa** [comment]
Hi @Weves , was there something wrong with my PR? I never received any feedback on it
