### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by arouene** [onyx-dot-app/onyx#3427]
Hello,

We have a Danswer host installed with docker. The host have 64GB of RAM, but vespa keeps getting killed for OOM. And then while it is restarted, the backend cannot reach again for vespa.

Memory:
```
# free -h
               total        used        free      shared  buff/cache   available
Mem:            62Gi        42Gi       2.6Gi       148Mi        18Gi        20Gi
Swap:             0B          0B          0B
```

Vespa getting killed for OOM:
```
[Tue Dec 10 17:20:04 2024] oom_reaper: reaped process 163083 (vespa-proton-bi), now anon-rss:0kB, file-rss:208kB, shmem-rss:0kB
```

Backend cannot reach vespa anymore:
```
ERROR:    12/11/2024 09:29:58 AM       handle_regular_answer.py  269: [Channel ID: D07EXAZES4U] Unable to process message - did not successfully answer in 5 attempts
Traceback (most recent call last):
  File "/app/danswer/document_index/vespa/chunk_retrieval.py", line 303, in query_vespa
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://index:8081/search/'
```

If I restart the backend container it's working again.

Is it normal for Danswer to require more than 64GB of memory?

**Comment by rkuo-danswer** [comment]
Hi Aroune, depends entirely on the number and size of the documents you are indexing.  Could you provide us with some more context?

**Comment by rkuo-danswer** [comment]
That is definitely a lot of docs, it may be necessary to add RAM to support that.  You can get a better feel for this by inspecting the memory usage of Vespa via the metrics endpoint.

https://docs.vespa.ai/en/operations/metrics.html
https://stackoverflow.com/questions/68014005/which-all-metric-to-trace-to-determine-if-the-resource-needs-to-be-added

**Comment by arouene** [comment]
Ok, so I as understand it seems pretty legit.
Thanks for the docs, I will take a peek !

**Comment by JonnyPower** [comment]
@rkuo-danswer we are experiencing a similar issue, is it expected that the index container's memory usage grows proportionately to number of indexed documents? 

that seems like a poor design decision if that's the case - acts more like a memory leak. isn't the Vespa database meant to prevent a need for loading every document in ram?

**Comment by rkuo-danswer** [comment]
> @rkuo-danswer we are experiencing a similar issue, is it expected that the index container's memory usage grows proportionately to number of indexed documents? 
> 
> that seems like a poor design decision if that's the case - acts more like a memory leak. isn't the Vespa database meant to prevent a need for loading every document in ram?

Not really ... in fact being in memory is a key component of being able to perform similarity searches across documents quickly.  There are probably some significant optimizations we can apply here, but generally speaking this is expected behavior.

**Comment by icebearlabs** [comment]
Hello, we. have a similar issue, however we don't index any new documents. RAM keeps creeping further up and up the more people interact with Danswer (through an API). 

We only have about 600 web pages indexed, which I feel should be easily handled. We add about 2-5 pages more per month.

**Comment by JonnyPower** [comment]
@lusob just curious, are you running the google drive connector? we're thinking there might be some duplicating of documents in the index from the drive connector, but haven't proven it yet

**Comment by lusob** [comment]
> [@lusob](https://github.com/lusob) just curious, are you running the google drive connector? we're thinking there might be some duplicating of documents in the index from the drive connector, but haven't proven it yet

I'm using only raw Markdown files, but thanks for letting me know about that issue!

**Comment by jzribi3** [comment]
Hello all, 
We have the same issue on our side. Have you found any workaround to limit the memory consumption?
Thanks!

**Comment by fuvidani** [comment]
Hi all,

we’re encountering the same issue. If this is expected behavior, it might be worth revisiting the [documentation](https://docs.onyx.app/production/aws/ec2#getting-an-instance). From the earlier comments, it seems that 16 GB RAM would rarely be sufficient for organizations with up to 5,000 users. We’re barely at 100 people and have experienced OOM issues with Onyx essentially from day one.

I’m also curious how Onyx manages this for Cloud customers. I understand that the self-hosted setup may offer little business incentive to investigate further, but I’d imagine this could be a similar pain point in a hosted environment.

**Comment by jawad-ali-71** [comment]
Hi @rkuo-danswer I am having the same issue when i run it through docker i try to upload a file which size is in KBs its indexing get stopped between and when i debugged the issue its because my docker is consuming complete 16Gb and its has no space left to perform indexing.
Can you tell me isn't there a solution that if we don’t want to use local models , instead we want to use Openai embeddings ada model direct so we can reduce the memory and shift from local model to Api endpoint.

**Comment by Kaddtechnologies** [comment]
Is this still an issue? How can this be stress tested in a controlled environment?

**Comment by jzribi3** [comment]
A solution is to use an external vector database instead of running it within the VM. To achieve this, a new class inheriting from DocumentIndex can be implemented

**Comment by Kaddtechnologies** [comment]
> A solution is to use an external vector database instead of running it within the VM. To achieve this, a new class inheriting from DocumentIndex can be implemented

Did this truly help? So you are saying to use something like pgvector on its own and not use the relational-dB?

**Comment by jzribi3** [comment]
Using an external vector database such as Qdrant Cloud, Elasticsearch, or Vespa Cloud etc. is often a better approach than running the vector index directly within the VM. The vector database is typically the component that demands the most memory. 

By offloading it, you can scale the vector store independently based on indexing and retrieval needs, instead of repeatedly scaling up the VM that hosts the full solution.
